export const CONFIG = {
  PORT: process.env.PORT || 3000,
  JWT_SECRET: process.env.JWT_SECRET || 'banking-app-secret-key-2025',
  JWT_EXPIRES_IN: '1h',
  JWT_REFRESH_EXPIRES_IN: '2h',
  PAGINATION_DEFAULT_LIMIT: 10,
  PAGINATION_MAX_LIMIT: 50
};

export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_001',
  TOKEN_EXPIRED: 'AUTH_002',
  TOKEN_INVALID: 'AUTH_003',
  UNAUTHORIZED: 'AUTH_004',
  ACCOUNT_NOT_FOUND: 'ACC_001',
  INSUFFICIENT_BALANCE: 'ACC_002',
  BENEFICIARY_NOT_FOUND: 'BEN_001',
  TRANSFER_NOT_FOUND: 'TRF_001',
  TRANSFER_ALREADY_CONFIRMED: 'TRF_002',
  TRANSFER_FAILED: 'TRF_003',
  CARD_NOT_FOUND: 'CARD_001',
  CARD_ALREADY_FROZEN: 'CARD_002',
  CARD_ALREADY_ACTIVE: 'CARD_003',
  VALIDATION_ERROR: 'VAL_001',
  INTERNAL_ERROR: 'INT_001'
};
